-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "askingPriceCents" SET DATA TYPE BIGINT,
ALTER COLUMN "revenueCents" SET DATA TYPE BIGINT,
ALTER COLUMN "ebitdaCents" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Mandate" ALTER COLUMN "ticketMinCents" SET DATA TYPE BIGINT,
ALTER COLUMN "ticketMaxCents" SET DATA TYPE BIGINT;
